### ISSUE TITLE
🐞 [Bug] 아이 수정 버그

### ISSUE THREAD

**Issue by wonu606** [Guzzing/Studay_Client#209]
## 🛠️ 어떤 버그를 고치나요?
- 잘못된 이름일 시, 버튼이 클릭되지 않고 에러 메시지도 출력하지 않습니다.
- 수정시 특정 학년만 수정 가능합니다.

## 링크
https://www.studay.me/edit/214/editing

## 사진
<img width="434" alt="image" src="https://github.com/Guzzing/Studay_Client/assets/133995055/77da54ad-6e75-457a-9233-5333c3147582">

<img width="484" alt="image" src="https://github.com/Guzzing/Studay_Client/assets/133995055/5d4dbc4f-1aca-4150-8021-8aeb191d1957">

**Comment by HeeSeok-kim** [comment]
/home/edit 페이지 입니다!
