### ISSUE TITLE
🐞 [Bug] 삭제가 진행되지 않는다. 

### ISSUE THREAD

**Issue by byeolhaha** [Guzzing/Studay_Client#270]
## ☑ TODOS
![image](https://github.com/Guzzing/Studay_Client/assets/108210958/2f54666d-b21d-4354-99bb-4cd740aa6e1b)

**Comment by HeeSeok-kim** [comment]
디테일 페이지에서 수정, 삭제를 진행하기로 변경되어 Close 처리하겠습니다.
