### ISSUE TITLE
🐞 [Bug] 해당 날짜에 두 개의 스케줄을 생성했는데 하나만 표시된다.

### ISSUE THREAD

**Issue by byeolhaha** [Guzzing/Studay_Client#295]
## ☑ TODOS
해당 날짜에 두 개의 스케줄을 생성했는데 하나만 표시된다.
응답값은 두개가 온다.
![image](https://github.com/Guzzing/Studay_Client/assets/108210958/e4d72e37-f583-4e57-a476-1d6cbba4aefc)

**Comment by HeeSeok-kim** [comment]
원인 찾았습니다!! 
한개만 보여지는게 아니고 아래 네비게이션바에 숨겨진 문제였습니다
CSS를 수정해보겠습니다.

<img width="398" alt="image" src="https://github.com/Guzzing/Studay_Client/assets/106604926/5f0d7288-5d39-41b2-9e99-7624a48ff182">

**Comment by HeeSeok-kim** [comment]
수정 완료되어서 PR올라갔습니다!
